routes/web.php
<?php

use App\Http\Controllers\ReservationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\CalendarOptionController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\DaysServiceController;
use App\Http\Controllers\ResourceController;
use App\Http\Controllers\DaysResourceController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\OpinionController;
use App\Http\Controllers\StatisticsController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NoteController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\MercadoPagoController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UpgradeController;
use App\Http\Controllers\DaysController;
use App\Http\Controllers\DaysUsersController;
use App\Http\Controllers\AbsenceController;
use App\Http\Controllers\TipController;
use App\Http\Controllers\WebController;
use App\Http\Controllers\FirstController;
use App\Http\Controllers\NoteClientController;
use App\Http\Controllers\WaitingController;
use App\Http\Controllers\VisitController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\IncidentController;
use App\Http\Controllers\BookingController;

use App\Http\Controllers\help\HelpController;

use App\Http\Controllers\root\RootHelpCategoryController;
use App\Http\Controllers\root\RootHelpPostController;
use App\Http\Controllers\root\RootHomeController;
use App\Http\Controllers\root\RootUserController;
use App\Http\Controllers\root\RootBusinessController;
use App\Http\Controllers\root\RootCodeController;
use App\Http\Controllers\root\RootAdminController;

Route::get('/'									, [HomeController::class, 'landing']);

Route::get('null', function()
{
	return "";
});

Route::get('comenzar'							, [AuthController::class, 'showRegistrationForm']);
Route::get('empezar'							, [AuthController::class, 'showRegistrationForm']);
Route::get('register'							, [AuthController::class, 'showRegistrationForm']);
Route::post('register'							, [AuthController::class, 'create']);
Route::get('ingresar'							, [AuthController::class, 'showLoginForm']);
Route::get('login'								, [AuthController::class, 'showLoginForm'])->name('login');
Route::post('login'								, [AuthController::class, 'login']);

Route::get('home'								, [HomeController::class, 'index'])->middleware('auth.basic');
Route::get('help'								, [HomeController::class, 'help'])->middleware('auth.basic');

Route::get('password/request'					, [AuthController::class, 'get_password_request']);
Route::post('password/request'					, [AuthController::class, 'set_password_request']);
Route::get('password/email/{ID}'				, [AuthController::class, 'get_password_email']);
Route::post('password/email/{ID}'				, [AuthController::class, 'set_password_email']);

Route::post('logout'							, [AuthController::class, 'logout']);

Route::get('disabled'							, [AuthController::class, 'get_disabled']);
Route::get('pending'							, [AuthController::class, 'get_pending']);
Route::get('expired'							, [AuthController::class, 'get_expired']);
Route::post('expired'							, [AuthController::class, 'set_expired']);
Route::get('invitation/{code}'					, [AuthController::class, 'get_invitation']);
Route::post('invitation/{code}'					, [AuthController::class, 'set_invitation']);

Route::get('ayuda'								, [HelpController::class, 'index']);
Route::get('ayuda/{slug}'						, [HelpController::class, 'post']);
Route::get('ayuda/categoria/{slug}'				, [HelpController::class, 'category']);
Route::get('ayuda/buscar/{slug}'				, [HelpController::class, 'search']);


Route::get('first/login'						, [FirstController::class, 'index'])->middleware('auth.admin');
Route::get('first/step1'						, [FirstController::class, 'index'])->middleware('auth.admin');
Route::get('first/step2'						, [FirstController::class, 'step2'])->middleware('auth.admin');
Route::get('first/step3'						, [FirstController::class, 'step3'])->middleware('auth.admin');
Route::get('first/finish'						, [FirstController::class, 'finish'])->middleware('auth.admin');

Route::resource('reservation'					, ReservationController::class)->middleware('auth.admin');
Route::get('delete/header'						, [ReservationController::class, 'header'])->middleware('auth.admin');
Route::get('delete/footer'						, [ReservationController::class, 'footer'])->middleware('auth.admin');

Route::resource('business'						, BusinessController::class)->middleware('auth.admin');
Route::get('business/delete/logo/{id}'			, [BusinessController::class, 'delete_logo'])->middleware('auth.admin');
Route::get('business/get/hours'					, [BusinessController::class, 'get_hours'])->middleware('auth.admin');
Route::post('business/set/hours'				, [BusinessController::class, 'set_hours'])->middleware('auth.admin');
Route::post('business/set/status'				, [BusinessController::class, 'set_status'])->middleware('auth.admin');
Route::get('business/generate/code'				, [BusinessController::class, 'generate_code'])->middleware('auth.admin');

Route::get('days/delete/{ID}'					, [DaysController::class, 'delete'])->middleware('auth.only');
Route::post('days/add'							, [DaysController::class, 'store'])->middleware('auth.only');

Route::resource('user'							, UserController::class)->middleware('auth.admin');
Route::get('user/delete/avatar/{id}'			, [UserController::class, 'delete_avatar'])->middleware('auth.basic');
Route::get('profile'							, [UserController::class, 'profile'])->middleware('auth');
Route::post('profile'							, [UserController::class, 'set_profile'])->middleware('auth');
Route::get('user/random/color'					, [UserController::class, 'get_random_color'])->middleware('auth.admin');
Route::get('user/get/hours/{ID}'				, [UserController::class, 'get_hours'])->middleware('auth.admin');
Route::post('user/set/hours'					, [UserController::class, 'set_hours'])->middleware('auth.admin');
Route::post('user/set/status'					, [UserController::class, 'set_status'])->middleware('auth.admin');

Route::get('daysUser/delete/{ID}'				, [DaysUsersController::class, 'delete'])->middleware('auth.admin');
Route::post('daysUser/add'						, [DaysUsersController::class, 'store'])->middleware('auth.admin');

Route::get('verify'								, [UserController::class, 'get_verify'])->middleware('auth.only');
Route::get('verify/{code}'						, [UserController::class, 'set_verify']);
Route::get('send/verify'						, [UserController::class, 'send_verify']);

Route::resource('notification'					, NotificationController::class)->middleware('auth.basic');
Route::get('view/notification'					, [NotificationController::class, 'view'])->middleware('auth.notification');
Route::get('read/notification'					, [NotificationController::class, 'read'])->middleware('auth.notification');

Route::resource('calendar'						, CalendarController::class)->middleware('auth.basic');
Route::post('manual/calendar'					, [CalendarController::class ,'manual'])->middleware('auth.basic');
Route::get('users/calendar/{ID}'				, [CalendarController::class ,'users'])->middleware('auth.basic');
Route::get('resources/calendar/{ID}'			, [CalendarController::class ,'resources'])->middleware('auth.basic');
Route::post('accept/calendar'					, [CalendarController::class ,'accept'])->middleware('auth.basic');
Route::post('refuse/calendar'					, [CalendarController::class ,'refuse'])->middleware('auth.basic');
Route::get('faild/calendar/{id}'				, [CalendarController::class ,'faild'])->middleware('auth.basic');
Route::get('reload/calendar'					, [CalendarController::class ,'reload']);
Route::get('count/calendar'						, [CalendarController::class ,'count']);

Route::resource('client'						, ClientController::class)->middleware('auth.basic');
Route::post('client/create/jquery'				, [ClientController::class, 'create_jquery'])->middleware('auth.basic');
Route::resource('note/client'					, NoteClientController::class)->middleware('auth.basic');
Route::resource('calendar_option'				, CalendarOptionController::class)->middleware('auth.basic');
Route::resource('statistics'					, StatisticsController::class)->middleware('auth.admin');
Route::resource('note'							, NoteController::class)->middleware('auth.basic');
Route::resource('media'							, MediaController::class)->middleware('auth.basic');
Route::resource('opinion'						, OpinionController::class)->middleware('auth.admin');
Route::resource('absence'						, AbsenceController::class)->middleware('auth.admin');
Route::resource('tips'							, TipController::class)->middleware('auth.admin');
Route::resource('waiting'						, WaitingController::class)->middleware('auth.admin');
Route::resource('visit'							, VisitController::class)->middleware('auth.admin');

Route::resource('service'						, ServiceController::class)->middleware('auth.admin');
Route::get('service/get/hours/{ID}'				, [ServiceController::class, 'get_hours'])->middleware('auth.admin');
Route::post('service/set/hours'					, [ServiceController::class, 'set_hours'])->middleware('auth.admin');
Route::post('service/set/status'				, [ServiceController::class, 'set_status'])->middleware('auth.admin');

Route::get('daysService/delete/{ID}'			, [DaysServiceController::class, 'delete'])->middleware('auth.admin');
Route::post('daysService/add'					, [DaysServiceController::class, 'store'])->middleware('auth.admin');

Route::resource('resource'						, ResourceController::class)->middleware('auth.admin');
Route::get('resource/get/hours/{ID}'			, [ResourceController::class, 'get_hours'])->middleware('auth.admin');
Route::post('resource/set/hours'				, [ResourceController::class, 'set_hours'])->middleware('auth.admin');

app/Http/Controllers/BusinessController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Business;
use App\Models\Days;
use App\Models\DaysUsers;
use Carbon\Carbon;
use Storage;
use File;
use Auth;

class BusinessController extends Controller
{
    private $path = "admin.business.";
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $business = Auth::user()->business;    
        return view($this->path."index", compact('business'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $old_short          = Business::where('code', $request->code)->first();
        $old_email          = Business::where('email', $request->email)->first();
        $business           = business();

        if(($old_short != null) and ($old_short->id != $business->id))
        {
            error(__('errors.repeat_code'));
            return back();
        }

        if(($old_email != null) and ($old_email->id != $business->id))
        {
            error(__('errors.repeat_user'));
            return back();
        }

        $file               = $request->file('logo');

        if($file != null)
        {
            if(file_exists($business->logo))
                unlink($business->logo);

            $nameFile           = "logo_".$business->id;
            Storage::disk('business')->put($nameFile.".".$file->getClientOriginalExtension(), File::get($file));
            
            $business->logo     = "storage/business/".$nameFile.".".$file->getClientOriginalExtension();
        }

        $business->name     = $request->name;
        $business->phone    = $request->phone;
        $business->email    = $request->email;
        $business->code     = $request->code;
        $business->rut      = $request->rut;
        $business->address  = $request->address;
        $business->save();

        foreach($business->users->where('business_hour', 'on') as $user)
        {
            $user->days()->delete();

            foreach(business()->days as $day)
            {
                $user_day                = new DaysUsers();
                $user_day->day           = $day->day;
                $user_day->start         = $day->start;
                $user_day->end           = $day->end;
                $user_day->status        = $day->status;
                $user_day->user_id       = $user->id;
                $user_day->save();
            }
        }

        l(
            user()->id,
            business()->id,
            "Empresa",
            "Editar",
            "Se editan los datos de la empreasa"
        );

        success(__('message.update_info'));
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
    }

    public function delete_logo($id)
    {
        $business = Business::findOrFail($id);

        if($business->id != Auth::user()->business_id)
        {
            error(__('errors.delete_logo'));
            return back();
        }

        if(file_exists($business->logo))
            unlink($business->logo);
        
        $business->logo = null; 
        $business->save();
        
        l(
            user()->id,
            business()->id,
            "Empresa",
            "Logo",
            "Se elimina logo"
        );
        
        success(__('message.delete_logo_info'));
        return back();
    }

    public function get_hours()
    {
        return view('admin.business.hour_table');
    }

    public function set_hours(Request $request)
    {
        $explode    = explode("_", $request->id);
        $time       = $explode[1];
        $id         = $explode[2];
        
        $day        = Days::findOrFail($id);
        $day[$time] = $request->val;
        $day->save();

        return true;
    }

    public function set_status(Request $request)
    {
        $day        = Days::find($request->id);
        
        if($day == null)
            return false;

        $days       = $day->business->days->where('day', $day->day);

        $status     = "on";
        if($request->status == "on")
            $status = "off";

        foreach($days as $day)
        {
            $day->status = $status;
            $day->save();
        }

        return true;
    }

    public function generate_code()
    {
        do {

            $code   = Random_Code(6);
            $exist  = Business::where('control_code', $code)->first();

        } while ($exist != null);

        $business   = business();
        $now        = Carbon::now();

        if(($business->control_date == null) or ($now->diffInMinutes($business->control_date) >= 30))
        {
            $business->control_code = $code;
            $business->control_user = user()->id;
            $business->control_date = Carbon::now();
            $business->save();
            
            return $code;
        }
        
        return $business->control_code;
    }
}

app/Http/Controllers/root/RootAdminController.php
<?php

namespace App\Http\Controllers\root;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class RootAdminController extends Controller
{
    public function index()
    {
        $git    = shell_exec('git show');
        $env    = file_get_contents(base_path('.env'));

        return view('root.admin.index', compact('env', 'git'));
    }

    public function git_pull()
    {
        $respuesta  = shell_exec('cd /home/lrlc0h5gdvkf/apps/tureserva && git pull');

        success('Respuesta desde el servidor: '.$respuesta);

        return back();
    }

    public function env_update(Request $request)
    {
        file_put_contents(base_path('.env'), $request->env);

        success('Se modifico archivo .env');

        return back();
    }
}

resources/views/root/business/index.blade.php
@extends('layouts.root', ['menu' => 'business'])

@section('title')
    Empresas
@endsection

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Empresas</h3>
            </div>
            <div class="card-body">
                <div class="table table-responsive">
                	<table class="table table-striped">
                		<tr>
                			<th>#</th>
                			<th>Nombre</th>
                			<th>Email</th>
                			<th>Telefono</th>
                			<th>Estado</th>
                			<th class="text-center">Ver</th>
                			<th class="text-center">Deshabilitar</th>
                			<th class="text-center">Reinstalar landing</th>
                			<th class="text-center">Tomar control</th>
                			<th class="text-center">Editar</th>
                			<th class="text-center">Eliminar</th>
                		</tr>
                		@foreach($businesses as $business)
							<tr>
								<td>{{$business->id}}</td>
								<td>{{$business->name}}</td>
								<td>{{$business->email}}</td>
								<td>{{$business->phone}}</td>
								<td>
									@if($business->status == "enabled")
										Habilitada
									@elseif($business->status == "pending")
										Pendiente
									@else
										Deshabilitada
									@endif
								</td>
								<td class="text-center">
									<a href="{{url('root/business', $business->id)}}" class="btn btn-success">
										<i class="fa fa-eye"></i>
									</a>
								</td>
								<td class="text-center">
									<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#disabled_{{$business->id}}">
										<i class="fas fa-exchange-alt"></i>
									</button>
									<!-- Modal -->

									<div class="modal fade deleteModal" id="disabled_{{$business->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
										<div class="modal-dialog modal-center" role="document">
											<div class="modal-content">
												<div class="modal-header bg-warning">
													<div class="col-12 text-right">
														<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													</div>
												</div>
												<div class="modal-body text-center">
													<div class="row">
														<div class="col-12 text-dark">
															<i class="fa fa-exchange-alt fa-4x"></i>
															<br>
															<h3>¿Cambiar estado de la empresa?</h3>
														</div>
													</div>
													<hr>
													<div class="row">
														<div class="col-6">
															<button type="button" class="btn btn-default btn-block" data-dismiss="modal">
																{{__('message.no')}}
															</button>
														</div>
														<div class="col-6">
															<a href="{{url('root/business/status', $business->id)}}" class="btn btn-warning btn-block">
																{{__('message.yes')}}
															</a>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</td>
								<td class="text-center">
									<button type="button" class="btn btn-info" data-toggle="modal" data-target="#landing_{{$business->id}}">
										<i class="fas fa-palette"></i>
									</button>
									<!-- Modal -->

									<div class="modal fade deleteModal" id="landing_{{$business->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
										<div class="modal-dialog modal-center" role="document">
											<div class="modal-content">
												<div class="modal-header bg-info">
													<div class="col-12 text-right">
														<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													</div>
												</div>
												<div class="modal-body text-center">
													<div class="row">
														<div class="col-12 text-dark">
															<i class="fas fa-palette fa-4x"></i>
															<br>
															<h3>¿Reinstalar landing?</h3>
														</div>
													</div>
													<hr>
													<div class="row">
														<div class="col-6">
															<button type="button" class="btn btn-default btn-block" data-dismiss="modal">
																{{__('message.no')}}
															</button>
														</div>
														<div class="col-6">
															<a href="{{url('root/business/landing', $business->id)}}" class="btn btn-info btn-block">
																{{__('message.yes')}}
															</a>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</td>
								<td class="text-center">
									<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#control_{{$business->id}}">
										<i class="fas fa-plug"></i>
									</button>
									<!-- Modal -->

									<div class="modal fade deleteModal" id="control_{{$business->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
										<div class="modal-dialog modal-center" role="document">
											<div class="modal-content">
												<div class="modal-header bg-dark">
													<div class="col-6">
														<h5>
															Tomar control
														</h5>
													</div>
													<div class="col-6 text-right">
														<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
													</div>
												</div>
												<div class="modal-body text-left">
													<div class="row">
														<div class="col-12 text-dark">
															<form action="{{url('root/business/control', $business->id)}}" class="form-horizontal" method="post">
																@csrf
																<div class="form-group">
																	<label for="">Codigo para conexión</label>
																	<input type="number" class="form-control" id="code_{{$business->id}}" name="code" placeholder="######">
																</div>
																<hr>
																<div class="row">
																	<div class="col-6">
																		<button type="button" class="btn btn-default btn-block" data-dismiss="modal">
																			{{__('message.no')}}
																		</button>
																	</div>
																	<div class="col-6">
																		<button class="btn btn-dark btn-block">
																			<i class="fa fa-plug"></i>
																			Conectar
																		</button>	
																	</div>
																</div>
															</form>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</td>	
								<td class="text-center">
									<a href="{{route('business.edit', $business->id)}}" class="btn btn-primary">
										<i class="fa fa-edit"></i>
									</a>
								</td>
								<td class="text-center">
									@include('helpers.delete_modal', ['delete_id' => $business->id, 'delete_route' => url('root/business', $business->id)])
								</td>
							</tr>
                		@endforeach
                	</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
	<script>
		$(document).ready(function()
		{
			@foreach($businesses as $business)
				$('#control_{{$business->id}}').on('shown.bs.modal', function () {
				  	$('#code_{{$business->id}}').trigger('focus')
				});
			@endforeach
		});
	</script>
@endsection